all: Program_1 Program_2

Program_1: Program_1.cpp Course.h Course.cpp
	g++ Program_1.cpp Course.cpp  -o Program_1

Program_2: Program_2.cpp  Instructor.h Instructor.cpp Course.h Course.cpp
	g++ Program_2.cpp Instructor.cpp Course.cpp -o Program_2


