all: Program_1 Program_2 Program_3 Program_4

Program_1: Program_1.cpp
	g++ Program_1.cpp -o Program_1

Program_2: Program_2.cpp
	g++ Program_2.cpp -o Program_2

Program_3: Program_3.cpp
	g++ Program_3.cpp -o Program_3

Program_4: Program_4.cpp
	g++ Program_4.cpp -o Program_4
